WIP: Use creep-away to downgrade guide count and cluster critical warns
sot/sparkles pull request #182
Opened 2023-03-06 14:08 UTC by jeanconn

## Description

For observations with man_angle_next <= 5deg:

- downgrade cluster warnings from critical to warning (is this too drastic)
- downgrade guide count warning in 3.5 to 4.0 range to warning

If this makes sense, needs updated tests.

Fixes #

## Interface impacts

## Testing

### Unit tests

- [ ] No unit tests
- [ ] Mac
- [ ] Linux
- [ ] Windows

Independent check of unit tests by [REVIEWER NAME]
- [ ] [PLATFORM]:

### Functional tests

No functional testing.

2023-04-03 13:41 UTC, taldcroft requested changes

2023-04-03 13:41 UTC, taldcroft commented on sparkles/core.py
> +        # Set critical guide_count threshold
Make this a bit tighter with:
```
if self.is_OR:
    count_lim = 3.5 if (self.man_angle_next <= CREEP_AWAY_THRESHOLD) else 4.0
else:
    count_lim = 6.0
```

2023-04-03 13:41 UTC, taldcroft commented on sparkles/core.py
> +        # Set critical guide_count threshold
Make this comment explain *why* this code is here, not *what* it does (which is already clear). Include a reference to the SSAWG page which discusses and approves this change.

2023-04-03 13:41 UTC, taldcroft commented on sparkles/tests/test_checks.py
> +    stars.add_fake_constellation(n_stars=5, mag=[7.0, 7.0, 7.0, 10.2, 10.3])
You can re-use the existing `stars`.

2023-04-03 13:41 UTC, taldcroft commented on sparkles/tests/test_checks.py
> +    aca = ACAReviewTable(aca)
Better to stick with the convention of `acar` for a generic review table `ACAReviewTable` and `aca` for the `ACATable`.  It just makes the code easier to read.

2023-04-03 13:41 UTC, taldcroft commented on sparkles/tests/test_checks.py
> +    # Set a scenario with guide_count in the 3.5 to 4.0 range and *but* with
Typo `and *but*`.

2023-04-03 13:41 UTC, taldcroft commented on sparkles/tests/test_checks.py
> +    aca = get_aca_catalog(**STD_INFO, man_angle_next=5, stars=stars, dark=DARK40)
Same, `5.0` not `5`.

2023-04-03 16:41 UTC, taldcroft commented on sparkles/tests/test_checks.py
> +    stars.add_fake_constellation(n_stars=5, mag=[7.0, 7.0, 7.0, 10.2, 10.3])
Actually, looking at this again, all of these individual tests within this function are independent. So they should each be a separate test. That way if one fails then you still test all the rest.

(My understanding of best practices for writing tests continues to improve and I now have a better appreciation for making unit tests atomic where possible).

2023-04-07 16:28 UTC, jeanconn commented on sparkles/core.py
> +                    msg += f' (man_angle_next > {CREEP_AWAY_THRESHOLD})'
Generally not, but I note the sparkles formatting is not fixed width anyway?  Different length agasc ids and the length of the line with the target coordinates look to push it around.

<img width="960" alt="Screen Shot 2023-04-07 at 12 26 04 PM" src="https://user-images.githubusercontent.com/791508/230643500-d59ec6b4-2e85-4aee-8275-8bb7766af408.png">

2023-04-07 16:30 UTC, jeanconn commented
Updated per comments.

2023-04-07 17:31 UTC, taldcroft approved these changes
LGTM, thanks!

2023-04-07 17:34 UTC, merged